[package]
name = "contents-title"
version = "0.1.0"
description = "Fetch videos and translate subtitles"
authors = ["eplin"]
edition = "2021"

[lib]
name = "contents_title_lib"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.53.1", features = ["process", "io-util", "macros", "rt-multi-thread", "sync", "time"] }
thiserror = "2.0.21"
async-trait = "0.1.92"
tauri-plugin-dialog = "2.8.0"
reqwest = { version = "0.13.5", default-features = false, features = ["json", "rustls", "http2"] }
futures = "0.3.34"


# Read the optimization guideline for more details: https://tauri.app/concept/size/#cargo-configuration
[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true

[dev-dependencies]
tempfile = "3.27.0"
